$(function(){
    $('.hidden_btn').click(function(){
        $('.hidden_wrap').stop().slideToggle();
    })
    $(window).resize(function(){
        if($(window).innerWidth()>768){
            $('.hidden_wrap').hide();
        }
    })
})